config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'reserve/:item_id', to: 'reserves#new', as: :reserve
  get 'reserves/check_out/:reserve_id', to: 'reserves#check_out',
                                        as: :checkout_reserve
  resources :reserves, except: [:new, :show]

  get 'check_in/:id', to: 'transactions#direct_checkin', as: :direct_checkin
  get '/transactions/student/:id', to: 'transactions#student_transactions',
                                  as: :student_activity
  get '/transactions/multiple_check_out', to: 'transactions#multiple_check_out',
                                          as: :multiple_check_out

  resources :transactions, except:[:show, :index, :new, :edit] do
    collection do
      get '/', to: 'transactions#notice'
      get :student
      get :display
      post :student_items
      post :edit_multiple
      put :update_multiple
    end
    member do
      get :check_in
      get :check_out
    end
  end

  devise_for :admins, skip: [:sessions],
                      :path_prefix => 'd',
                      controllers: { registrations: "registrations" }
  as :admin do
    get 'sign_in', to: 'devise/sessions#new', as: :new_admin_session
    post 'sign_in', to: 'devise/sessions#create', as: :admin_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  resources :blogs
  get '/admin_blogs', to: 'blogs#admin_blogs', as: :admin_blogs

  get '/items/new', to: 'items#select', as: :new_item
  post '/items/new', to: 'items#select'
  get '/items/new/:class', to: 'items#new'
  get '/items/see/:class', to: 'items#category', as: :category
  get '/search', to: 'items#search', as: :search
  get '/items/:id/transactions', to: 'items#transactions', as: :item_transactions
  get '/items/download', to: 'items#download', as: :download_items #items export

  get '/admins', to: 'admins#index', as: :admins
  delete '/admins/:id', to: 'admins#destroy', as: :admin

  resources :items,  except:[:new]

  root 'static#home'
  get 'static/admin_home'

  resources :item_requests

  resources :psa_posts

  # export links
  get '/reserves/download', to: 'reserves#download', as: :download_reserves
  get '/transactions/download', to: 'transactions#download', as: :download_transactions
  get '/augmented/download', to: 'admins#download', as: :download_augmented

end

app/views/shared/_error_msg.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(item.errors.count, "errors") %>.
    </div>
    <ul>
      <% item.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_reserves.html.erb
<div class="reserves index">
  <table class="table table-bordered table-striped listing" id="form">
    <tr class="header">
      <th>Student ID</th>
      <th>Student Email</th>
      <th>Item Name</th>
      <th>Pick-up Date</th>
      <th>Due Date</th>
      <th>Actions</th>
    </tr>
    <% unless @reserves.size == 0 %>
      <% @reserves.each do |reserve| %>
      <tr>
        <td><%= reserve.student_id %></td>
        <td><%= reserve.email %></td>
        <td><%= link_to reserve.item.name, item_path(reserve.item_id) %></td>
        <td><%= reserve.start_date.strftime("%a, %B %d, %Y") %></td>
        <td><%= reserve.end_date.strftime("%a, %B %d, %Y") %></td>
        <td class="actions">
          <%= link_to("Edit", edit_reserf_path(reserve), class: "btn btn-info")%>
          <%= link_to("Check Out", checkout_reserve_path(reserve.id), class: "btn btn-success" )%>
          <%= link_to("Delete", reserf_path(reserve), method: :delete,class: "btn btn-danger", data: { confirm: 'Are you sure you want to delete this reservation?'}) %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/shared/_transactions.html.erb
<div class="transactions notice">

  <table class="table table-bordered table-striped listing" id="form">
    <tr class="header">
      <th>Student ID</th>
      <th>Student Email</th>
      <th>Item Name</th>
      <th>Pick-up Date</th>
      <th>Due Date</th>
      <th>Returned Date</th>
      <th>Actions</th>
    </tr>
    <% unless @transactions.nil? || @transactions.size == 0 %>
      <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.student_id %></td>
        <% if transaction.item.rentable%>
          <% if transaction.email.blank? %>
            <td>UNAVAILABLE</td>
          <% else %>
            <td><%= transaction.email %></td>
          <% end %>
        <% else %>
          <td>NON-RETURNABLE</td>
        <% end %>
        <td><%= link_to transaction.item.name, item_path(transaction.item) %></td>
        <td><%= transaction.start_date.strftime("%a, %B %d, %Y") %></td>
        <% if transaction.item.rentable %>
          <td><%= transaction.end_date.strftime("%a, %B %d, %Y") %></td>
          <% if transaction.return_date == nil %>
            <td style='color:red;'>Item not returned</td>
          <% else %>
            <td><%= transaction.return_date.strftime("%a, %B %d, %Y") %></td>
          <% end %>
          <td class="actions">
            <% if transaction.return_date.nil? %>
            <%= link_to "Check in", direct_checkin_path(transaction),
                class: "btn btn-info" %>
            <% else %>
              <%= link_to "Edit", check_in_transaction_path(transaction),
                  class: "btn btn-info" %>
            <% end %>
            <%= link_to "Delete", transaction_path(transaction),
                                method: :delete,
                                data: { confirm: "Are you sure you want to delete this transaction?" },
                                class: "btn btn-danger" %>
          </td>
        <% else %>
          <td>UNAVAILABLE</td>
          <td>NON-RETURNABLE</td>
          <td class="actions">
            <%= link_to "Check In", "#", class: "btn btn-link disabled" %>
            <%= link_to "Delete", transaction_path(transaction),
                                  method: :delete,
                                  data: { confirm: "Are you sure you want to delete this transaction?" },
                                  class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </table>
</div>