config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'reserve/:item_id', to: 'reserves#new', as: :reserve
  get 'reserves/check_out/:reserve_id', to: 'reserves#check_out',
                                        as: :checkout_reserve
  resources :reserves, except: [:new, :show]

  get 'check_in/:id', to: 'transactions#direct_checkin', as: :direct_checkin
  get '/transactions/student/:id', to: 'transactions#student_transactions',
                                  as: :student_activity
  get '/transactions/multiple_check_out', to: 'transactions#multiple_check_out',
                                          as: :multiple_check_out

  resources :transactions, except:[:show, :index, :new, :edit] do
    collection do
      get '/', to: 'transactions#notice'
      get :student
      get :display
      post :student_items
      post :edit_multiple
      put :update_multiple
    end
    member do
      get :check_in
      get :check_out
    end
  end

  devise_for :admins, skip: [:sessions],
                      :path_prefix => 'd',
                      controllers: { registrations: "registrations" }
  as :admin do
    get 'sign_in', to: 'devise/sessions#new', as: :new_admin_session
    post 'sign_in', to: 'devise/sessions#create', as: :admin_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  resources :blogs
  get '/admin_blogs', to: 'blogs#admin_blogs', as: :admin_blogs

  get '/items/new', to: 'items#select', as: :new_item
  post '/items/new', to: 'items#select'
  get '/items/new/:class', to: 'items#new'
  get '/items/see/:class', to: 'items#category', as: :category
  get '/search', to: 'items#search', as: :search
  get '/items/:id/transactions', to: 'items#transactions', as: :item_transactions
  get '/items/download', to: 'items#download', as: :download_items #items export

  get '/admins', to: 'admins#index', as: :admins
  delete '/admins/:id', to: 'admins#destroy', as: :admin

  resources :items,  except:[:new]

  root 'static#home'
  get 'static/admin_home'

  resources :item_requests

  resources :psa_posts

  # export links
  get '/reserves/download', to: 'reserves#download', as: :download_reserves
  get '/transactions/download', to: 'transactions#download', as: :download_transactions
  get '/augmented/download', to: 'admins#download', as: :download_augmented

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authorize_admin

  def notice
    unreturned = Transaction.where(return_date: nil).desc(:updated_at)
    #returned = Transaction.where(:return_date.ne =>  nil).desc(:updated_at)
    @transactions = returns_only(unreturned)
  end

  def download
      send_data dumpTransactions, filename: 'transactions.csv'
  end

  def display
    unreturned = Transaction.where(return_date: nil).desc(:updated_at)
    returned = Transaction.where(:return_date.ne =>  nil).desc(:updated_at)
    nonreturn = non_returns_only(unreturned)

    @transactions = returned + nonreturn
  end

  def create
    qty_tosave = params[:quantity].to_i
    @transaction = Transaction.new(transaction_params)

    if check_out_n_items(qty_tosave)
      flash[:notice] = "Check out successful."
      redirect_to(:action => 'notice')
      return
    else
        flash.now[:alert] = "Couldn't find #{qty_tosave} " +
                            "#{'item'.pluralize(qty_tosave)} for " +
                            "the given dates!"
        @item = Item.find(params.require(:transaction)[:item_id])
        render 'check_out'
        return
    end
  end

  def check_in
    @transaction = Transaction.find(params[:id])
  end

  def update
    #Find a new object using form parameters
    @transaction = Transaction.find(params[:id])
    @item = @transaction.item
    # update and persist to DB
    if @transaction.update_attributes(transaction_params)
      #If save succeeds, redirect to the show action
      flash[:notice] = "Transaction updated successfully."
      redirect_to static_admin_home_path
    else
      #If save fails, redisplay the form so user can fix problems
      render 'check_in'
    end
  end

  def direct_checkin
    #Find a new object using form parameters
    transaction = Transaction.find(params[:id])
    if checkin_transaction(transaction)
      flash[:notice] = "Checked in successfully."
    else
      flash[:alert] = "Check in failed." # this should never happen
    end
    redirect_back fallback_location: {action: 'notice'}
  end

  def destroy
    transaction = Transaction.find(params[:id])
    result = delete_transaction(transaction)
    if result
      flash[:notice] = "Transaction destroyed successfully."
    else
      flash[:alert] = "Transaction could not be deleted."
    end
    redirect_back fallback_location: {action: 'notice'}
  end

  def student
    @transaction=Transaction.new()
    #just form for Student id (just input for student id)
  end

  def student_items
    std_id = params[:transaction][:student_id]
    redirect_to student_activity_path(std_id)
  end

  def student_transactions
    @transactions  = Transaction.where(student_id: params[:id]).all
  end


  def check_out
    @item = Item.find(params[:id])
    @transaction = Transaction.new()
  end

  def multiple_check_out
    if params.has_key?(:transaction)
      @transaction = Transaction.new(transaction_params)
    else
      @transaction = Transaction.new()
    end

    if params.has_key?(:sku)
      @item = Item.find_by(_SKU: params[:sku])

      if params[:transaction][:student_id].to_s.size != 9
        redirect_to multiple_check_out_path, alert: "Student ID has to be 9 digits long!"
        return
      end

      if params.has_key?(:checkout)
        if @item.rentable
          if params[:transaction][:end_date] == ""
            redirect_to multiple_check_out_path(transaction: transaction_params,
                                                sku: params[:sku], qty: params[:qty]),
                                                alert: "End date cannot be empty!"
            return
          end
          if params[:transaction][:email] == ""
            redirect_to multiple_check_out_path(transaction: transaction_params,
                                                sku: params[:sku], qty: params[:qty]),
                                                alert: "Email is required for rentable items!"
            return
          end
        end

        qty = params[:qty].to_i
        if check_out_n_items(qty)
          redirect_to multiple_check_out_path(transaction: transaction_params),
                                              notice: "Checked out successfully!"
        else
          redirect_to multiple_check_out_path(transaction: transaction_params,
                                              sku: params[:sku], qty: params[:qty]),
                                              alert: "Items not available for the given dates!"
        end
      end# end of !if params key
    end # end of if params key
  end #end of method

  private
    def transaction_params
      params.require(:transaction).permit(:student_id, :item_id, :start_date,
                                      :end_date, :return_date, :email,:status)
    end

    def returns_only(transactions)
      returnables = []
      transactions.each do |t|
        if t.item.rentable
          returnables << t
        end
      end

      return returnables
    end

    def non_returns_only(transactions)
      returnables = []
      transactions.each do |t|
        unless t.item.rentable
          returnables << t
        end
      end

      return returnables
    end

    def delete_transaction(transaction)
      item = transaction.item
      # if the transaction is not checked in
      if transaction.return_date.nil?
        item._quantity.push(transaction.qty_id)
        if !item.rentable
          item.quantity += 1
        end
      end

      return transaction.destroy && item.save
    end

    def checkin_transaction(transaction)
      item = transaction.item
      # update item info
      if (item.rentable && transaction.return_date.nil?)
        item._quantity.push(transaction.qty_id)
      end

      transaction.return_date = DateTime.now
      if item.buffer_period == 0
        transaction.status = true
      end
      return transaction.save && item.save
    end

    def check_out_unrentable(transaction,item)
      picked_id = item._quantity.pop()
      if picked_id.nil?
        return false
      else
        transaction.qty_id = picked_id
        item.quantity -= 1
        return (transaction.save && item.save)
      end
    end

    def check_out_rentable(transaction,item)
      start_date = transaction.start_date
      end_date = transaction.end_date

      picked_id = pick_available_checkout(item,start_date,end_date)

      if !(picked_id)
        return false
      else
        item._quantity.delete(picked_id)
        transaction.qty_id = picked_id
        return (transaction.save && item.save)
      end
    end

    def undo_transactions(transactions)
      transactions.each do |t|
        t.destroy
      end
    end

    def check_out_n_items(qty_tosave)
      saved_transactions = []
      saved_qtys = []
      (1..qty_tosave).each do
        transaction = Transaction.new(transaction_params)
        item = @transaction.item
        if item.rentable
          result = check_out_rentable(transaction,item)
        else
          result = check_out_unrentable(transaction,item)
        end

        if result
          saved_transactions.push(transaction)
          saved_qtys.push(transaction.qty_id)
        else
          undo_transactions(saved_transactions)
          item._quantity += saved_qtys
          if !item.rentable
            item.quantity += saved_qtys.size
          end
          item.save
          return false
        end
      end
      return true
    end

    def dumpTransactions()
        header_names = ["Student ID","Email","Pick-up date", "Due date","Returned on","Item name", "Item SKU"]
        field_list = ["student_id","email","start_date","end_date"]
        all_trasactions = Transaction.all
        CSV.generate(headers: true) do |csv|
            csv << header_names # CSV Header
            all_trasactions.each do |transaction|
                csv_arr = []
                field_list.each do |f_name|
                    csv_arr.push(transaction[f_name])
                end
                rt_date = (transaction.status) ? transaction.return_date : "Not returned Yet!"
                csv_arr.push(rt_date)
                item = transaction.item
                csv_arr.push(item.name)
                csv_arr.push(item._SKU)
                csv << csv_arr
            end
        end
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/check_in.html.erb
<div id="form">
  <h2>Check In!</h2>
  <%= simple_form_for @transaction, url: {action: 'update'}, method: :patch do |f| %>

      <%= f.input :student_id, label: "Student ID", required: true, as: :integer, readonly: true %>
      <%= f.hidden_field :item_id, value: "#{@transaction.item.id}", readonly: true%>
      <%= f.input :start_date, label: "Pick-up Date", as: :date, readonly: true, html5: true  %>
      <%= f.input :end_date, label: "Return Date", as: :date, readonly: true, html5: true  %>
      <%= f.input :return_date, label: "Item Returned On", as: :date,
                                input_html: {min: Date.today},
                                html5: true  %>



      <%= f.input :status, as: :boolean,label: "Is the item already available to be checked out again? (Check if yes)"%>
      <% buffer = @transaction.item.buffer_period %>
      <%= "If you don't check this, the item will be ready #{buffer} " +
          "#{'day'.pluralize(buffer)} after its return date."  %><br><br>

      <%= f.submit "Check In", class: "btn btn-success" %>
  <% end %>
</div>

app/views/transactions/check_out.html.erb
<%= link_to("<< Back to Item",item_path(@item.id), :class => 'back-link')%>

  <div id="form">
    <h2>Check Out</h2>
    <%= simple_form_for @transaction, :url => transactions_path, :method => 'post' do |f| %>

        <%= f.input :student_id, label: "Student ID", required: true, as: :integer%>
        <% if @item.rentable%>
          <%= f.input :email, label: "Student Email" %>
        <% end %>
        <%= f.hidden_field :item_id, :value => "#{@item.id}", :readonly => true%>
        <%= f.input :start_date, label: "Start Date",as: "date",
                          input_html: {min: Date.today},
                          html5: true  %>
        <% if @item.rentable%>
          <%= f.input :end_date, label: "End Date", required: true, as: "date",
                        input_html: {min: Date.today},
                        html5: true  %>
        <% end %>
        <%= label :quantity,"Quantity" %><br>
        <%= number_field_tag :quantity, 1 ,min: 1, max: @item._quantity.size%>
        <br><br>
        <%= f.submit "Check Out", class: "btn btn-success" %>
    <% end %>
  </div>

app/views/transactions/delete.html.erb
<%= link_to("<< Back to Transactions", {:action => 'notice'}, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Transaction</h2>

  <!-- <%#= form_for(@subject, :method => 'delete') do |f| %> -->
  <%= form_for(@transaction, :url => transaction_path(@transaction), :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this transaction?</p>

    <div class="form-buttons">
      <%= f.submit("Delete Transaction") %>
    </div>

  <% end %>
</div>

app/views/transactions/dipslay.html.erb
<%= link_to("<<Back to Unreturned Transactions", {:controller => 'transactions', :action => 'notice'}, :class => 'back-link')%>
  <h2>Transaction Log: Returned/Non-returnables</h2>
<% provide(:destination, 'display')%
<%= render 'shared/transactions' %>

app/views/transactions/display.html.erb
<%= link_to("See Unreturned Transactions", {:controller => 'transactions', :action => 'notice'}, :class => 'back-link')%>
  <h2>Transaction Log: Returned/Non-returnables</h2>
<%= render 'shared/transactions' %>

app/views/transactions/multiple_check_out.html.erb
<div class="multiple-check-out">
  <div id="form">
    <h2>Multiple Check Out</h2>
    <%= simple_form_for @transaction, url: multiple_check_out_path, method: :get do |f| %>
      <div class="multi-checkout-static">
        <%= f.input :student_id, label: "Student ID", required: true, as: :integer %>
        <%= f.input :email, label: "Email (required for rentable items)", required: false %>
        <%= label_tag :sku, "Enter Item SKU" %><br>
        <%= text_field_tag :sku, params[:sku], placeholder: "Enter SKU of an item",
                                required: true %>
        <%= submit_tag "Check SKU", name: :submit, class: "btn btn-link" %>
      </div>
      <% if @item != nil %>
        <%= f.hidden_field :item_id, :value => "#{@item.id}", :readonly => true%>
        <div class="valid-SKU">
          <p><%= @item.name %></p>
        </div>
        <div class="quantity">
          <p>Quantity: <%= number_field_tag :qty, params[:qty] || 1, min: 1,
                            max: @item._quantity.size,
                            :required => true  %></p>
        </div>
        <div class="start-date">
          <%= f.input :start_date, as: :date, label: "Start Date", value: Date.today,
                                  input_html: {min: Date.today}, html5: true %>
        </div>
        <% if @item.rentable %>
          <div class="end-date">
            <%= f.input :end_date, as: :date, label: "End Date",
                                    input_html: {min: Date.today}, html5: true %>
          </div>
        <% end %>
      <% elsif params.has_key?(:sku) %>
        <div class="invalid-SKU">
          <p>Invalid SKU</p>
        </div>
      <% end %>
      <div class="buttons">
        <% if @item != nil %>
          <%= submit_tag "Checkout", name: :checkout, class: "btn btn-success" %>
        <% end %>
        <%= link_to "Done", static_admin_home_path, class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>

app/views/transactions/notice.html.erb
<%= link_to(">> See Returned and Non-returnable transactions", display_transactions_path, :class => 'back-link')%>
<h2>Transaction Log</h2>
<%= render 'shared/transactions' %>

app/views/transactions/student.html.erb
<div id='form'>
  <h3>Please enter the Student's ID</h3>
  <%= simple_form_for @transaction,url: {action: :student_items} do |form| %>
    <%= form.input :student_id, label: "Student ID", as: :integer, required: true %>
    <%= form.submit "Submit", class: "btn btn-success"%>
  <% end %>
</div>

app/views/transactions/student_check_in.html.erb
<h1>Please enter the Student's id</h1>
<div>
  <%= form_tag(student_item_check_transactions_path, :method => :post) do %>
      <%= text_field_tag :input %>
      <%= submit_tag ("Submit to Check In") %>
  <% end %>
</div>

app/views/transactions/student_transactions.html.erb
<h3>Student transactions</h3>
<%= render 'shared/transactions'%>