config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'reserve/:item_id', to: 'reserves#new', as: :reserve
  get 'reserves/check_out/:reserve_id', to: 'reserves#check_out',
                                        as: :checkout_reserve
  resources :reserves, except: [:new, :show]

  get 'check_in/:id', to: 'transactions#direct_checkin', as: :direct_checkin
  get '/transactions/student/:id', to: 'transactions#student_transactions',
                                  as: :student_activity
  get '/transactions/multiple_check_out', to: 'transactions#multiple_check_out',
                                          as: :multiple_check_out

  resources :transactions, except:[:show, :index, :new, :edit] do
    collection do
      get '/', to: 'transactions#notice'
      get :student
      get :display
      post :student_items
      post :edit_multiple
      put :update_multiple
    end
    member do
      get :check_in
      get :check_out
    end
  end

  devise_for :admins, skip: [:sessions],
                      :path_prefix => 'd',
                      controllers: { registrations: "registrations" }
  as :admin do
    get 'sign_in', to: 'devise/sessions#new', as: :new_admin_session
    post 'sign_in', to: 'devise/sessions#create', as: :admin_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_admin_session
  end

  resources :blogs
  get '/admin_blogs', to: 'blogs#admin_blogs', as: :admin_blogs

  get '/items/new', to: 'items#select', as: :new_item
  post '/items/new', to: 'items#select'
  get '/items/new/:class', to: 'items#new'
  get '/items/see/:class', to: 'items#category', as: :category
  get '/search', to: 'items#search', as: :search
  get '/items/:id/transactions', to: 'items#transactions', as: :item_transactions
  get '/items/download', to: 'items#download', as: :download_items #items export

  get '/admins', to: 'admins#index', as: :admins
  delete '/admins/:id', to: 'admins#destroy', as: :admin

  resources :items,  except:[:new]

  root 'static#home'
  get 'static/admin_home'

  resources :item_requests

  resources :psa_posts

  # export links
  get '/reserves/download', to: 'reserves#download', as: :download_reserves
  get '/transactions/download', to: 'transactions#download', as: :download_transactions
  get '/augmented/download', to: 'admins#download', as: :download_augmented

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Lula Bell's Resource Center</title>
    <%= Gon::Base.render_data %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Pacifico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <nav id="mainNav" class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Lula Bell's", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Items", items_path %>
            </li>
            <li>
              <%= link_to "Request", new_item_request_path %>
            </li>
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
              </li>
              <li>
                <%= link_to "Admin Home", static_admin_home_path %>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_admin_session_path %>
              </li>
            <% end %>
            <li>
              <%= form_tag(search_path, method: 'get', class: "navbar-form navbar-right", role: "search", enforce_utf8: false) do %>
                <div class="input-group">
                  <%= text_field_tag :query, params[:query], class: "search-query form-control", placeholder: "Search"%>
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                      <i class="glyphicon glyphicon-search"></i>
                    </button>
                  </div>
                </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='main-body-content'>
      <div class="flashes" style="max-width: 50%; margin: auto">
        <% if flash[:notice] && flash[:notice] != "" %>
          <div class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] && flash[:alert] != "" %>
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <div class="footer-left" style="display:inline; float:left">
          <p>&copy; 2017 Lula Bell's Resource Center. All Rights Reserved.</p>
          <ul class="list-inline">
            <li>
                <a href="#">Contact Us</a>
            </li>
          </ul>
          <p>Created by <a href=http://pronto.davidson.edu/>Project PRONTO</a> - Jose Balcazar, Andre Hidalgo, Hermon Mulat, Anubhav Roy Bhattacharya, Laurie Heyer</p>
        </div>
        <div class="footer-right" style="float:right">
          <div class="list-inline footer-right" style="display:inline">
            <li>
              <a href="https://www.instagram.com/lula_bells_/" target="_blank"><i class="fa fa-instagram fa-3x"></i></a>
            </li>
            <li>
              <a href="https://orgsync.com/162523/chapter" target="_blank" id='wildcat_sync'><%= image_tag("wildcat_logo.png", size:"36x42") %></a>
            </li>
          </div>
          <p></p>
          <a href="https://www.davidson.edu" target="_blank"><%= image_tag("logo.png", size:"100x23") %></a>
        </div>
      </div>
    </footer>

  </body>
</html>